### PR TITLE
Fix VTKHDF Output (partially) and High-Order Fused Volume+Surface Output

### LINKED ISSUE #1339: vtkhdf is broken on master (working fine with v1.3.1)?
### Describe the bug

I'm running tpv13 from SeisSol/Training, on 1 node, o4, single precision on supermuc, intel 2023.1.0
I enabled vtkhdf output with:
```diff
diff --git a/tpv13/parameters.par b/tpv13/parameters.par
index 367c296..b38d81d 100644
--- a/tpv13/parameters.par
+++ b/tpv13/parameters.par
@@ -36,7 +36,7 @@ printtimeinterval_sec = 1.0                    ! Time interval at which output w
 OutputMask = 1 1 1 1 1 1 1 1 1 1 1             ! turn on and off fault outputs
 refinement_strategy = 2
 refinement = 1
-!vtkorder = 3
+vtkorder = 3
 /
 
 !parameterize ascii fault file outputs
@@ -61,14 +61,16 @@ ClusteredLTS = 2                               ! Enable local time-stepping
 
 &Output
 OutputFile = 'output/tpv13'
 Format = 6                                     ! Format (10=no output, 6=hdf5 output)
+WavefieldOutput = 1
 !             |stress     |vel
 iOutputMask = 0 0 0 0 0 0 1 1 1
 !                 |strain     |eta
 iPlasticityMask = 0 0 0 0 0 0 1
-TimeInterval =  4.                           ! Index of printed info at time
 refinement = 1
 
+wavefieldvtkorder = 2
+TimeInterval = 2.
+
 ! Free surface output
 SurfaceOutput = 1
 SurfaceOutputRefinement = 0
@@ -90,7 +92,7 @@ Checkpoint = 0
 /
 
 &AbortCriteria
-EndTime = 8.0
+EndTime = 2.0
 /
```
and I'm checking that vtk is able to read the file with 

```python
import vtk

for fname in [
    "output/tpv13-wavefield-0.vtkhdf",
    "output/tpv13-fault-elementwise-0.vtkhdf",
]:
    reader = vtk.vtkHDFReader()
    reader.SetFileName(fname)
    reader.Update()
    output = reader.GetOutputDataObject(0)
    print(fname, output.GetNumberOfPoints())
```
with v1.3.1:
di73yeq4@login03:/hppfs/scratch/0A/di73yeq4/Training/tpv13> python test.py 
output/tpv13-fault-elementwise-0.vtkhdf 15640
output/tpv13-wavefield-0.vtkhdf 370340

with master:
di73yeq4@login03:/hppfs/scratch/0A/di73yeq4/Training/tpv13> python test.py 
output/tpv13-wavefield-0.vtkhdf 0
output/tpv13-fault-elementwise-0.vtkhdf 0

### Expected behavior

vtk able to read point in the vtkhdf

job file (using one node, one rank to avoid problems with ASYNC already documented in https://github.com/SeisSol/SeisSol/issues/1228)

```bash
#!/bin/bash

# Job Name and Files (also --job-name)
#SBATCH -J fl33
#Output and error (also --output, --error):
#SBATCH -o ./%j.%x.out
#SBATCH -e ./%j.%x.out

#Initial working directory:
#SBATCH --chdir=./

#Notification and type
#SBATCH --mail-type=END
#SBATCH --mail-user=thomas.ulrich@lmu.de
#SBATCH --no-requeue
#SBATCH --export=ALL
#SBATCH --account=pn49ha
#SBATCH --ntasks-per-node=1
#EAR may impact code performance
#SBATCH --ear=off
#SBATCH --nodes=1 --partition=test --time=00:30:00

module load slurm_setup

#Run the program:
export MP_SINGLE_THREAD=no
unset KMP_AFFINITY
#export OMP_NUM_THREADS=46
#export OMP_PLACES="cores(23)"
export OMP_NUM_THREADS=94
export OMP_PLACES="cores(47)"
#Prevents errors such as experience in Issue #691
export I_MPI_SHM_HEAP_VSIZE=8192

export XDMFWRITER_ALIGNMENT=8388608
export XDMFWRITER_BLOCK_SIZE=8388608
export SC_CHECKPOINT_ALIGNMENT=8388608

export SEISSOL_CHECKPOINT_ALIGNMENT=8388608
export SEISSOL_CHECKPOINT_DIRECT=1
export ASYNC_MODE=THREAD
export ASYNC_BUFFER_ALIGNMENT=8388608
source /etc/profile.d/modules.sh

echo 'num_nodes:' $SLURM_JOB_NUM_NODES 'ntasks:' $SLURM_NTASKS
ulimit -Ss 2097152

ORDER=${order:-4}
echo "specified order: $order"
module load seissol/1.3.1-intel23-o${ORDER}-elas-dunav-single-impi
#module load seissol/march2025-intel23-o${ORDER}-elas-dunav-single-impi

part_file=$1

mapfile -t filenames < "$part_file"

# Iterate over the array of filenames
for filename in "${filenames[@]}"; do
    echo "Processing file: $filename"
    srun SeisSol_Release_sskx_${ORDER}_elastic $filename
done
```

### PR DESCRIPTION
**Pull request by davschneller**
As the title says:

* fix a bug regarding non-distributed Hdf5 writes (they weren't written at all after #1238 ) Most likely fixes #1339 .
* add support for fused high-order volume/surface output (there's still performance optimization potential for it, though)

Any high-order fault output requires #1364 first.

### CODE REVIEW

File: src/IO/Writer/File/Hdf5Writer.cpp [hunk 1]
```diff
@@ -224,7 +224,7 @@ void Hdf5File::writeData(const async::ExecInfo& info,
     const auto [memspace, space] = [&]() -> std::pair<hid_t, hid_t> {
       if (nullstart.empty()) {
         return {h5memspace, h5space};
-      } else if (source->distributed() && writeLength[0] > 0) {
+      } else if (writeLength[0] > 0 || !source->distributed()) {
```
Comment (vikaskurapati) [inline src/IO/Writer/File/Hdf5Writer.cpp:227]: Just out of curiosity. I don't understand why this needed to be changed.

Comment (davschneller) [reply src/IO/Writer/File/Hdf5Writer.cpp:227]: What was going on here is: if `source->distributed()` is false, we still need to write the data (that's done for metadata like the number of points or cells); but that wasn't happening (thus the data was set to zero).

Thus, the change. The other case where we'll need to write is if we have something distributed, and we need to write it (which is the `writeLength[0] > 0`).

**Comment by davschneller** [comment]
Yes—fully agreed w.r.t. testing. Tbh; the whole IO complex will need unit tests sooner or later now (on my list; but may take time)—but yes, end-to-end tests would also be great to have. If I think about it—we may need to have some mesh comparison scripts first probably.
