### PR TITLE
Fix incomplete type for `unique_ptr`

### LINKED ISSUE #1124: compile issue on SupermucNG
**Describe the bug**
Error during compilation:

```
[ 41%] Building CXX object CMakeFiles/SeisSol-common-lib.dir/src/ResultWriter/AnalysisWriter.cpp.o
/dss/lrzsys/sys/spack/release/22.2.1/opt/x86_64/gcc/11.2.0-gcc-bmnv5vk/include/c++/11.2.0/bits/unique_ptr.h(83): error: incomplete type is not allowed
  	static_assert(sizeof(_Tp)>0,
  	                     ^
          detected during:
            instantiation of "void std::default_delete<_Tp>::operator()(_Tp *) const [with _Tp=seissol::kernels::PointSourceCluster]" at line 361
            instantiation of "std::unique_ptr<_Tp, _Dp>::~unique_ptr() noexcept [with _Tp=seissol::kernels::PointSourceCluster, _Dp=std::default_delete<seissol::kernels::PointSourceCluster>]" at line 59 of "/dss/dsshome1/07/ru76tuj2/SeisSol_20240607/src/SourceTerm/typedefs.hpp"

[ 42%] Building CXX object CMakeFiles/SeisSol-common-lib.dir/src/SourceTerm/NRFReader.cpp.o
compilation aborted for /dss/dsshome1/07/ru76tuj2/SeisSol_20240607/src/SourceTerm/PointSource.cpp (code 2)
make[2]: *** [CMakeFiles/SeisSol-common-lib.dir/build.make:706: CMakeFiles/SeisSol-common-lib.dir/src/SourceTerm/PointSource.cpp.o] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:290: CMakeFiles/SeisSol-common-lib.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Expected behavior**
Code should compile.

**To Reproduce**
1. Which version do you use? Provide branch and commit id.
main 60aedc8c2ae0a5d9e5a46cc3a40e4eaf1c047225
2. Which build settings do you use? Which compiler version do you use?
`cmake -DNUMA_AWARE_PINNING=ON -DASAGI=ON -DCMAKE_BUILD_TYPE=Release -DHOST_ARCH=skx -DPRECISION=double -DORDER=4 -DGEMM_TOOLS_LIST=PSpaMM ..`
4. On which machine does your problem occur? If on a cluster: Which modules are loaded?
Documented supermucNG spack build:
image

**Additional context**
Compilation works with commit 6d301757378ad8446173e0a12c095a695a708aaf

### PR DESCRIPTION
**Pull request by davschneller**
Fixes #1124 .

### CODE REVIEW

File: src/SourceTerm/Manager.cpp [hunk 1]
```diff
@@ -288,7 +288,8 @@ auto makePointSourceCluster(ClusterMapping mapping,
                             const unsigned* meshIds,
                             seissol::initializer::LTSTree* ltsTree,
                             seissol::initializer::LTS* lts,
-                            seissol::initializer::Lut* ltsLut) -> PointSourceClusterPair {
+                            seissol::initializer::Lut* ltsLut)
+    -> seissol::kernels::PointSourceClusterPair {
```
Comment (vikaskurapati) [inline src/SourceTerm/Manager.cpp:292]: Is the indentation off or is this how it is intended to be?

Comment (davschneller) [reply src/SourceTerm/Manager.cpp:292]: The formatter likes it like that. Not my decision tbh :) .

**Review by Thomas-Ulrich — APPROVED** [review]
I don't really understand the solution, but there is nothing which looks harmful there ;-)
