### PR TITLE
Fixes #333

### LINKED ISSUE #333: Inconsistent number of elements in the surface output
**Describe the bug**
I have performed a series of simulations with various point source locations under the same mesh. However, the total number of elements in each surface output slightly differ with each.

**Expected behavior**
I expect the total number of elements in the output remains the same when not altering the mesh file or any other related parameters.

### PR DESCRIPTION
**Pull request by uphoffc**

### CODE REVIEW

File: src/Solver/FreeSurfaceIntegrator.cpp [hunk 1]
```diff
@@ -233,10 +233,15 @@ void seissol::solver::FreeSurfaceIntegrator::initializeSurfaceLTSTree(  seissol:
 {
   seissol::initializers::LayerMask ghostMask(Ghost);
 
+  auto const is_duplicate = [&ghostMask, ltsLut](unsigned ltsId) {
+    return ltsId != ltsLut->ltsId(ghostMask, ltsLut->meshId(ghostMask, ltsId));
+  };
+
```
Comment (krenzland) [inline src/Solver/FreeSurfaceIntegrator.cpp:239]: 1) Name should be formatted like isDuplicate
2) Probably should be called isUnique, as it is only used in the negated form

**Review by krenzland — CHANGES_REQUESTED** [review]
Looks good! One minor comment. Haven't tested it but I don't think it breaks anything.

**Review by krenzland — APPROVED** [review]
